config/routes.rb
Rails.application.routes.draw do

  

	resources :chatrooms do
  		resource :chatroom_users
  		resources :messages

  	end

	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	root to: 'pages#home'



	resources :articles


	#  get "/articles" index
	#  post "/articles"	create
	#  delete "/articles/:id" delete
	#  get "/articles/:id" show
	#  get "articles/new" new
	#  get "/articles/:id/edit" edit
	#  patch "/articles/:id" update
	#  put "/articles/:id" update
	
  	# Serve websocket cable requests in-process
	mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, uniqueness: true
	validates :body, presence: true, length: {minimum: 20}
	validates :location, presence: true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
has_many :chatroom_users
has_many :users, through: :chatroom_users
has_many :messages
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user

  	scope :current, -> { order(created_at: :desc).limit(5) }

  	def as_json(options = {})
   		MessageSerializer.new(self).as_json
  	end
  	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook,:google_oauth2]
  
  has_many :chatroom_users
  has_many :chatroom, through: :chatroom_users
  has_many :messages

  def self.new_with_session(params, session)
		super.tap do |user|
    		if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      			user.email = data["email"] if user.email.blank?
    		end
  		end
	end

  def self.new_with_session(params, session)
    super.tap do |user|
        if data = session["devise.google_data"] && session["devise.google_data"]["extra"]["raw_info"]
            user.email = data["email"] if user.email.blank?
        end
      end
  end

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    user.image = auth.info.image # assuming the user model has an image
	  end
	end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#GET /articles
	def index
		@articles =	Article.all
	end
	#GET /articles/:id
	def show
		@article = Article.find(params[:id])
	end

	#Get /articles/new

	def new
		@article = Article.new
	end

	#POST /articles
	def create
		@article = Article.new( title: params[:article][:title],
								body: params[:article][:body],
								location: params[:article][:location])
		if @article.save
			@user = current_user
			ActionCorreoMailer.welcome_email(@user).deliver
			redirect_to @article
		else
			render :new
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(title: params[:article][:title],
							body: params[:article][:body],
							location: params[:article][:location])
			redirect_to @article
		else
			render :edit
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_chatroom

	def create
		@chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
		redirect_to @chatroom
	end

	def destroy
		@chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
		redirect_to chatrooms_path
	end

	private 
	def set_chatroom
		@chatroom= Chatroom.find(params[:chatroom_id])
	end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_chatroom

	def create
		message = @chatroom.messages.new(message_params)
		message.user = current_user
		message.save
		redirect_to '/#'
		MessageRelayJob.perform_later(message)
	end

	private

	def set_chatroom
		@chatroom = Chatroom.find(params[:chatroom_id])
	end

	def message_params
		params.require(:message).permit(:body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  def google_oauth2
     
    @user = User.from_omniauth(request.env["omniauth.auth"])
 
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
			<% @article.errors.full_messages.each do |message| %>
				<div class="be-green be-blue field"> <%= message %></div>
			<%end%>
			<div class="field">
				<%= f.text_field :title, placeholder: "Nombre Del Sitio Turistico", class:"form-control" %>
			</div>
			<div class="field">
				<%= f.text_area :body, placeholder: "Informacion Del Sitio",style:"height:250px", class:"form-control"%>
			</div>
			<div class="field">
				<%= f.text_field :location, placeholder: "Localizacion Del Sitio", class:"form-control"%>
			</div>
			<% if current_user %>
			<div class="field">
					<%=current_user.email%>
			</div>
			<% end %> 

			<div class="field">
				<%= f.submit "Guardar", class:"btn btn-primary" %>
			</div>
<%end%>

app/views/articles/edit.html.erb
<div style="width:80%; padding-top: 60px">
	<h1 class="be-blue"> Editar Informacion Del Sitio Turistico</h1>
	<%= render "form" %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1 style="padding-top: 60px" class="be-blue"><%= link_to article.title, article%></h1> 
	<div><h4 class ="be-blue">Informacion: </h4><%= article.body%></div>
	<% if current_user %>
	<div><h4 class ="be-blue">Autor: </h4><%=current_user.email%></div>
	<%end%>
	<div><h4 class ="be-blue">Localizacion: </h4><%= article.location %> - <%= link_to "Eliminar", article, method: :delete, class:"botton-blue"%>
	</div>
	<div>___________________________________________________________</div>

<%end%>

app/views/articles/new.html.erb
<div style="width:80%; padding-top: 50px">
	<h1 class="be-blue"> Crear Informacion Del Sitio Turistico</h1>
	<%= render "form" %>	
</div>

app/views/articles/show.html.erb
<h1 style= "padding-top: 60px" class="be-blue"><%= @article.title %></h1>
<div><h3> Informacion Del Sitio</h3><%= @article.body %></div>
<div><h3> Localizacion Del Sitio</h3><%= @article.location %></div>
<% if current_user %>
<div><h3> Autor </h3><%=current_user.email%> </div>
<%end%>
<div><%=link_to "Editar", edit_article_path(@article), class:"botton-blue"%></div>

app/views/chatrooms/_form.html.erb
<%= form_for(chatroom) do |f| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chatrooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.name %></td>
        <td><%= link_to 'Show', chatroom %></td>
        <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
        <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Join', chatroom_chatroom_users_path(chatroom), method: :post%></td>
        <td><%= link_to 'Leave', chatroom_chatroom_users_path(chatroom), method: :delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1 style="padding-top: 50px">Nueva Sala De Chat</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<style type="text/css">
	.panel{
		background-color: #5960b6;
	}
</style>
<div class="panel panel-default full-height" style="padding-top: 30px">
	<div class="panel-heading">
		Bienvenido <strong><%= current_user.name  %></strong> Se Encuentra En La Sala:<strong><%= @chatroom.name  %></strong> 
		
	</div>

	<div class="panel-body full-height bottom-padding">
		<div class="messages-list full-height">
			<div data-behavior="messages" data-chatroom-id="<%= @chatroom.id %>">
				<% @messages.each do |message| %>
					<%= render message %>
				<%end%>	
			</div>
		</div>
	</div>

	<div class="panel-footer chat-text-input">
		<%= form_for [@chatroom, Message.new] do |f| %>
			<%= f.text_area :body, rows: 1, class: "form-control", autufocus: true%>
		<%end%>
	</div>  

	<!--	<p class="col-md" style="padding-top: 50px">
		  <h2><strong>Sala:</strong><small><%= @chatroom.name %></small></h2>
		  
		</p>


		<li class="col-md" type="none">
			<div data-behavior="messages" data-chatroom-id="<%= @chatroom.id %>">
				<% @messages.each do |message| %>
					<%= render message %>
				<%end%>	
			</div>
		</li>

		<%= form_for [@chatroom, Message.new] do |f| %>
			<%= f.text_area :body, rows: 1, class: "form-control", autufocus: true%>
		<%end%>-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eje Tour</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>
  <style type="text/css">
    body{
     color: #ffffff;
    }
  </style>
  <style type="text/css">
    .navbar-default {
  background-color: #5960b6;
  border-color: #6b7d85;
}
.navbar-default .navbar-brand {
  color: #fdffff;
}
.navbar-default .navbar-brand:hover,
.navbar-default .navbar-brand:focus {
  color: #eeeeee;
}
.navbar-default .navbar-text {
  color: #fdffff;
}
.navbar-default .navbar-nav > li > a {
  color: #fdffff;
}
.navbar-default .navbar-nav > li > a:hover,
.navbar-default .navbar-nav > li > a:focus {
  color: #eeeeee;
}
.navbar-default .navbar-nav > li > .dropdown-menu {
  background-color: #5960b6;
}
.navbar-default .navbar-nav > li > .dropdown-menu > li > a {
  color: #fdffff;
}
.navbar-default .navbar-nav > li > .dropdown-menu > li > a:hover,
.navbar-default .navbar-nav > li > .dropdown-menu > li > a:focus {
  color: #eeeeee;
  background-color: #6b7d85;
}
.navbar-default .navbar-nav > li > .dropdown-menu > li > .divider {
  background-color: #6b7d85;
}
.navbar-default .navbar-nav .open .dropdown-menu > .active > a,
.navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover,
.navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
  color: #eeeeee;
  background-color: #6b7d85;
}
.navbar-default .navbar-nav > .active > a,
.navbar-default .navbar-nav > .active > a:hover,
.navbar-default .navbar-nav > .active > a:focus {
  color: #eeeeee;
  background-color: #6b7d85;
}
.navbar-default .navbar-nav > .open > a,
.navbar-default .navbar-nav > .open > a:hover,
.navbar-default .navbar-nav > .open > a:focus {
  color: #eeeeee;
  background-color: #6b7d85;
}
.navbar-default .navbar-toggle {
  border-color: #6b7d85;
}
.navbar-default .navbar-toggle:hover,
.navbar-default .navbar-toggle:focus {
  background-color: #6b7d85;
}
.navbar-default .navbar-toggle .icon-bar {
  background-color: #fdffff;
}
.navbar-default .navbar-collapse,
.navbar-default .navbar-form {
  border-color: #fdffff;
}
.navbar-default .navbar-link {
  color: #fdffff;
}
.navbar-default .navbar-link:hover {
  color: #eeeeee;
}

@media (max-width: 767px) {
  .navbar-default .navbar-nav .open .dropdown-menu > li > a {
    color: #fdffff;
  }
  .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover,
  .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
    color: #eeeeee;
  }
  .navbar-default .navbar-nav .open .dropdown-menu > .active > a,
  .navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover,
  .navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
    color: #eeeeee;
    background-color: #6b7d85;
  }
}
  </style>
  
  <body>
  <div class="container">
    <br>
  	<header>
  		<nav class="navbar navbar-default navbar-fixed-top ">
  			<div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar1">
              <span class="sr-only"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand"><strong>EjeTour</strong></a>
          </div>


          <div class="collapse navbar-collapse" id="navbar1">
            <ul class="nav navbar-nav">
              <li><%= link_to "Inicio", root_path%></li>
              <li><%= link_to "Sitios Turisticos", articles_path%></li>
              <li><%= link_to "Agregar Sitios Turisticos", new_article_path%></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Sesión <span class="caret"></span>
                </a>
                  <ul class="dropdown-menu">
                    <li><a href="">
                    <% unless current_user %>
                      <%= link_to "Iniciar Sesión Con Google", user_google_oauth2_omniauth_authorize_path %>
                    <% end %></a></li>
                    <li><a href="">
                    <% unless current_user %>
                       <%= link_to "Iniciar Sesión Con Facebook", user_facebook_omniauth_authorize_path %>
                    <% else %>
                      <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
                    <% end %></a></li>
                  </ul>
              </li>
              
              <li><% 
                if current_user %>
                  <strong><%=current_user.name%></strong> <%= image_tag(current_user.image, size: "50x50") %>
                <% end %></li>
            </ul>

            <% if current_user %>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Salas De Chat<span class="caret"></span>
                </a>
                  <ul class="dropdown-menu">
                    <li><a href="">
                    <% current_user.chatroom.each do |chatroom| %>
                      <li><%= link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %></li>
                    <%end%>
                    </a></li>
                  </ul>
              </li>
            </ul>
            <%end%>
          </div>
         
  	</header>
  	
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div><strong><%= message.user.name %></strong> <%= message.body%></div>

app/views/messages/create.js.erb
$("#new_message")[0].reset()

app/views/pages/home.html.erb
<h1 style="padding-top: 50px">Bienvenido</h1>

<% if current_user %>
	<div> <%=current_user.email%></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>